version: "3.8"

services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - 5432:5432
    restart: on-failure
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - db-data:/var/lib/postgresql/data
    init: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      - ./frontend/mount:/frontend
    init: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    # tty: true
    # stdin_open: true
    container_name: backend
    ports:
      - 3333:3333
      - 5555:5555
    restart: on-failure
    env_file:
      - .env
    networks:
      - ft_transcendence
    depends_on:
      - dev-db
    volumes:
      - ./backend/mount:/backend
    init: true

volumes:
  db-data:
    name: db-data

networks:
  ft_transcendence:
    name: ft_transcendence
