version: "3.8"

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - transcendence
    # will cause a problem with bind-mount volumes ?
    volumes:
      - db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    restart: always
    env_file:
      - ./backend/.env.test
    networks:
      - transcendence

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    env_file:
      - ./frontend/.env
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - transcendence
    depends_on:
      - dev-db
      - test-db

volumes:
  db-data:
    name: "db-data"

networks:
  transcendence:
