version: '3.8'
services:
    dev-db:
        image: postgres:13
        ports:
            - 5434:5432
        restart: always
        env_file:
            - .env
        networks:
            - transcendence

    test-db:
        image: postgres:13
        ports:
            - 5435:5432
        restart: always
        env_file:
            - .env.test
        networks:
            - transcendence

networks:
    transcendence:
